fix: true               # default: false
parallel: true          # default: false
format: progress        # default: Standard::Formatter
# ruby_version: 2.3.3     # default: RUBY_VERSION
default_ignores: false  # default: true

ignore:                 # default: []
  - 'config/puma.rb'
  - 'db/schema.rb'
  - 'vendor/**/*'
  # - 'test/**/*':
  #   - Layout/AlignHash
