version: '2.4'

services:
  postgres:
    image: postgres:12.3-alpine
    volumes:
      - .docker/.psqlrc:/root/.psqlrc:ro
      - postgres:/var/lib/postgresql/data
      - ./log:/root/log:cached
    environment:
      POSTGRES_PASSWORD: password
      PSQL_HISTFILE: /root/log/.psql_history
    ports:
      - 7001:5432
    healthcheck:
      test: pg_isready -U postgres -h 127.0.0.1
      interval: 5s

  redis:
    image: redis:6.0-alpine
    volumes:
      - redis:/data
    ports:
      - 7002:6379
    healthcheck:
      test: redis-cli ping
      interval: 1s
      timeout: 3s
      retries: 30

volumes:
  postgres:
  redis:
