default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV.fetch("DATABASE_URL") { "postgres://postgres:password@localhost:7001" } %>

development:
  <<: *default
  database: small_cinema_development

test:
  <<: *default
  database: small_cinema_test


staging:
  <<: *default
  database: small_cinema_staging

production:
  <<: *default
  database: small_cinema_production
